spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ms-graph-gateway
    username:
    password:


#placeholders. Do not add creds
azure:
  timeout: 1
  credentials:
    clientid: XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    clientsecret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    tenantguid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    entobjectid: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX