spring:
  profiles:
    include:
      - kafka
      - db
server:
  port: 8080

logging:
  pattern:
    console: "%d{dd.MM.yyyy HH:mm:ss.SSSXXX} %highlight(%-5level) %logger{0} - %msg%n"
  level:
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.flywaydb: DEBUG
    no.novari: INFO

novari:
  application-id: fint-kontroll-ms-graph-gateway
  org-id: fintlabs.no
  kafka:
    topic:
      org-id: fintlabs-no
      domain-context: kontroll
    application-id: fintlabs.no
    default-replicas: 1
fint:
  kontroll:
    ms-graph-gateway:
      user:
        #Set variable user Attributes. Case sensitive. See User Object in Graph
        use-same-id-num-attribute: false
        user-id-num-attribute: employeeId
        validator-attribute: employeeType
        student-validator: elev
        employee-validator: tilsett
        employeeidattribute: onPremisesExtensionAttributes.extensionAttribute10
        studentidattribute: onPremisesExtensionAttributes.extensionAttribute9
        mainorgunitidattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitId
        mainorgunitnameattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitName
        enableexternalusers: false
        externaluserattribute: onPremisesExtensionAttributes.extensionAttribute11
        externaluservalue: ----
        userpagingsize: 999
        stale-after-days: 21
        accepted-deviation-percent: 5
        min-not-seen-count: 7
        user-scheduler:
            delta:
              fixed-delay-ms: 450000
              initial-delay-ms: 1000
            full-import:
              cron: 0 0 12 * * *



