apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-ms-graph-gateway
  app.kubernetes.io/instance: fint-kontroll-ms-graph-gateway_fintlabs-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fintlabs-no.kontroll.*"
      - op: add
        path: "/spec/resources"
        value: 
          limits:
            memory: "3Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
      - op: add
        path: "/spec/env/0"
        value:
          name: "JAVA_TOOL_OPTIONS"
          value: "-XX:+ExitOnOutOfMemoryError -Xmx3072m"
      - op: add
        path: "/spec/env/1"
        value:
          name: "fint.org-id"
          value: "fintlabs.no"
    target:
      kind: Application
      name: fint-kontroll-ms-graph-gateway
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-api-vault/items/kontroll-ms-graph-gateway-fintlabs-api"
    target:
      kind: OnePasswordItem
      name: fint-kontroll-ms-graph-gateway