apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-ms-graph-gateway
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-ms-graph-gateway:latest
  imagePullPolicy: Always
  env:
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-ms-graph-gateway'
    - name: fint.kontroll.authorization.authorized-role
      value: "https://role-catalog.vigoiks.no/vigo/kontroll/user"
    - name: fint.kontroll.authorization.authorized-org-id
      value: "vigo.no"
  envFrom:
    - secretRef:
        name: fint-kontroll-ms-graph-gateway
  database:
    database: fint-kontroll
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
