apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-ms-graph-gateway
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  replicas: 1
  image: ghcr.io/fintlabs/fint-kontroll-ms-graph-gateway:latest
  imagePullPolicy: Always
  env:
    - name: "JAVA_TOOL_OPTIONS"
      value: "-XX:+ExitOnOutOfMemoryError -Xmx2048m"
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-ms-graph-gateway'
    - name: fint.kontroll.authorization.authorized-role
      value: "https://role-catalog.vigoiks.no/vigo/kontroll/user"
    - name: fint.kontroll.authorization.authorized-org-id
      value: "vigo.no"
    - name: management.endpoints.web.base-path
      value: "/actuator"
    - name: management.endpoints.web.exposure.include
      value: "prometheus,health,info"
    - name: management.endpoint.prometheus.enabled
      value: "true"

  envFrom:
    - secretRef:
        name: fint-kontroll-ms-graph-gateway
  database:
    database: fint-kontroll
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.entity.resource-group*'
        permission: read
      - topic: 'fintlabs-no.kontroll.event.resource-group*'
        permission: read
      - topic: 'fintlabs-no.kontroll.entity.graph-*'
        permission: admin
      - topic: 'fintlabs-no.kontroll.event.graph-*'
        permission: admin


  observability:
      metrics:
          enabled: true
          port: "8080"
          path: '/actuator/prometheus'
