name: MD

on:
    workflow_dispatch:
        inputs:
            cluster:
                description: 'Select an environment'
                required: true
                default: 'warning'
                type: choice
                options:
                    - aks-beta-fint-2021-11-23
                    - aks-api-fint-2022-02-08

            org:
                description: 'Select organisation'
                required: true
                default: 'warning'
                type: choice
                options:
                    - fintlabs-no
                    - ofk-no
                    - bfk-no
                    - afk-no
                    - fridiks-no
                    - nfk-no
                    - vlfk-no

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    CLUSTER_NAME: ${{ inputs.cluster }}
    ORG: ${{ inputs.org }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Get environment
              uses: actions/github-script@v8
              id: environment
              with:
                  script: return '${{ inputs.cluster }}'.split('-')[1]
                  result-encoding: string

            - name: Get resource group name
              uses: actions/github-script@v8
              id: resource-group
              with:
                  script: return 'rg-aks-${{ steps.environment.outputs.result }}'
                  result-encoding: string

            - name: Print deployment configuration
              run: |
                  echo "Cluster: $CLUSTER_NAME"
                  echo "Resource group: ${{ steps.resource-group.outputs.result }}"
                  echo "Environment: ${{ steps.environment.outputs.result }}"
                  echo "OrgId: $ORG"

            - name: Log in to the Container registry
              uses: docker/login-action@v4
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v6
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short

            - name: Build and push Docker image
              uses: docker/build-push-action@v7
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Bake manifests with Kustomize
              uses: azure/k8s-bake@v4
              id: bake
              with:
                  renderEngine: kustomize
                  kustomizationPath: kustomize/overlays/${{ steps.environment.outputs.result }}/${{ env.ORG }}

            - name: Login to Azure
              uses: azure/login@v3
              with:
                  creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"

            - name: Setup kubelogin
              uses: azure/use-kubelogin@v1.3
              with:
                  kubelogin-version: v0.2.12

            - name: Set target cluster
              uses: azure/aks-set-context@v5
              with:
                  cluster-name: ${{ env.CLUSTER_NAME }}
                  resource-group: ${{ steps.resource-group.outputs.result }}
                  admin: 'true'
                  use-kubelogin: 'true'

            - name: Deploy
              uses: azure/k8s-deploy@v6
              with:
                  action: deploy
                  manifests: ${{ steps.bake.outputs.manifestsBundle }}
                  images: ${{ steps.meta.outputs.tags }}
                  namespace: ${{ env.ORG }}
